---
language: minimal

services:
  - docker

jobs:
  include:
    - stage: test
      if: NOT branch = main
      script: docker-compose build --build-arg PHP_IMAGE_TAG=8.0-fpm-alpine3.13 lumen && docker-compose up -d db && docker-compose up lumen
    - script: docker-compose build --build-arg PHP_IMAGE_TAG=7.4-fpm-alpine3.13 lumen && docker-compose up -d db && docker-compose up lumen

    - stage: deploy
      script: docker-compose build --build-arg PHP_IMAGE_TAG=7.4-fpm-alpine3.13 deploy-prod && docker-compose up deploy-prod
      if: branch = main
