# DO NOT USE FOR PRODUCTION !!! DO NOT USE FOR PRODUCTION !!!
#
# docker-compose.yml for quick and easy DEV environment setup
#
# DO NOT USE FOR PRODUCTION !!! DO NOT USE FOR PRODUCTION !!!

---
version: "3.3"

services:
  lumen:
    image: php:8.0-fpm-alpine
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    env_file:
      - dev.env
    command: mysqld
    volumes:
      - ./.dev-mysql-data:/var/lib/mysql:rw
