# DO NOT USE FOR PRODUCTION !!! DO NOT USE FOR PRODUCTION !!!
#
# docker-compose.yml for quick and easy DEV environment setup
#
# DO NOT USE FOR PRODUCTION !!! DO NOT USE FOR PRODUCTION !!!

---
version: "2.4"

services:
  lumen:
    container_name: ctvero-lumen
    build: docker
    ports:
      - 8000:8000
    environment:
      - TRAVIS_JOB_ID
    volumes:
      - .:/var/www/html
    command: /entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ctvero-db
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=homestead
      - MARIADB_USER=homestead
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
      - TZ=Europe/Prague
    volumes:
      - ./.dev-mysql-data:/var/lib/mysql:Z
    ports:
      - 3306:3306
    healthcheck:
      test: sh -c 'echo SELECT 1 | mysql -psecret'
      interval: 5s
      timeout: 5s
      retries: 100
