# DO NOT USE FOR PRODUCTION !!! DO NOT USE FOR PRODUCTION !!!
#
# docker-compose.yml for quick and easy DEV environment setup
#
# DO NOT USE FOR PRODUCTION !!! DO NOT USE FOR PRODUCTION !!!

---
version: "2.4"

services:
  lumen:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    command: sh -c 'php artisan migrate && php -S lumen:8000 -t public'
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10
    restart: always
    env_file:
      - dev.env
    volumes:
      - ./.dev-mysql-data:/var/lib/mysql:Z
    ports:
      - 3306:3306
    healthcheck:
      test: sh -c 'echo SELECT 1 | mysql -psecret'
      interval: 5s
      timeout: 5s
      retries: 100
