---
name: CI

concurrency: oneatatime

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    environment: oneatatime
    steps:
      - uses: actions/checkout@v2
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
      - name: Run PHP 8.0 tests
        run: |
          docker-compose build --build-arg PHP_IMAGE_TAG=8.0-fpm-alpine3.13 lumen
          docker-compose up -d db
          UID_GID="$(id -u):$(id -g)" docker-compose up lumen
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
      - name: Run PHP 7.4 tests
        run: |
          docker-compose build --build-arg PHP_IMAGE_TAG=7.4-fpm-alpine3.13 lumen
          docker-compose up -d db
          UID_GID="$(id -u):$(id -g)" docker-compose up lumen
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
  deploy:
    runs-on: self-hosted
    environment: oneatatime
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
      - name: Deploy to production
        run: |
          docker-compose build --build-arg PHP_IMAGE_TAG=7.4-fpm-alpine3.13 deploy-prod
          UID_GID="$(id -u):$(id -g)" docker-compose up deploy-prod
        env:
          CTVERO_DEPLOY_PROD_SECRET: ${{ secrets.CTVERO_DEPLOY_PROD_SECRET }}
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
