---
name: Prod

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: fivaldi/ctvero-rocnich-obdobi/.github/workflows/test.yml@main

  prod:
    runs-on: self-hosted
    concurrency: prod
    environment: prod
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
      - name: Deploy to production
        run: |
          docker-compose build --build-arg PHP_IMAGE_TAG=7.4-fpm-alpine3.13 deploy-prod
          UID_GID="$(id -u):$(id -g)" docker-compose up deploy-prod
        env:
          CTVERO_DEPLOY_PROD_SECRET: ${{ secrets.CTVERO_DEPLOY_PROD_SECRET }}
      - name: Clean up
        run: |
          docker-compose down --rmi all -v --remove-orphans
          git clean -dfx
